alpha_c: 0.674149;
beta: 0.5;

f(x,y) := 4 * alpha_c * x * (1 - x) + beta * y * (1 - x);
g(x,y) := 4 * alpha_c * y * (1 - y) + beta * x * (1 - y);

with_stdout("results.dat, printf(true, "  y"));

solutions: solve([f(x,y) = x, g(x, y) = y], [x, y]);

with_stdout("results.dat",for i: 1 thru length(solutions) do
	printf(true, "~7,5f ~7,5f~%",float(rhs(first(solutions[i]))),float(rhs(second(solutions[i]))))
);


